"use client";

import axios from "axios";
import Link from "next/link";
import { ChangeEvent, useCallback, useEffect, useState } from "react";
import { AppFrame } from "@/components/AppFrame";
import { ProtectedRoute } from "@/components/ProtectedRoute";
import { WorkflowBadge } from "@/components/WorkflowBadge";
import { ApiError, api } from "@/lib/api";
import { DocumentType, downloadDocument, fileSize, InternshipOnboarding, InternshipSource, sourceOptions } from "@/lib/internship-onboarding";

export default function InternshipOnboardingPage() {
  const [onboarding, setOnboarding] = useState<InternshipOnboarding | null>(null); const [loading, setLoading] = useState(true);
  const [busy, setBusy] = useState(""); const [error, setError] = useState(""); const [diaryConfirmed, setDiaryConfirmed] = useState(false);
  const load = useCallback(async () => { try { setOnboarding((await api.get<InternshipOnboarding>("/student/internship-onboarding")).data); } catch { setError("Internship onboarding could not be loaded."); } finally { setLoading(false); } }, []);
  useEffect(() => { void load(); }, [load]);
  function message(cause: unknown) { return axios.isAxiosError<ApiError>(cause) ? cause.response?.data?.message ?? "The request could not be completed." : "The request could not be completed."; }
  async function secure() { setBusy("secure"); setError(""); try { setOnboarding((await api.post<InternshipOnboarding>("/student/internship-onboarding/secure")).data); } catch (cause) { setError(message(cause)); } finally { setBusy(""); } }
  async function selectSource(source: InternshipSource) { setBusy("source"); setError(""); try { setOnboarding((await api.put<InternshipOnboarding>("/student/internship-onboarding/source", { source })).data); } catch (cause) { setError(message(cause)); } finally { setBusy(""); } }
  async function upload(type: DocumentType, event: ChangeEvent<HTMLInputElement>) { const file = event.target.files?.[0]; event.target.value = ""; if (!file) return; setBusy(type); setError(""); const body = new FormData(); body.append("file", file); try { setOnboarding((await api.post<InternshipOnboarding>(`/student/internship-onboarding/documents/${type}`, body, { headers: { "Content-Type": "multipart/form-data" } })).data); } catch (cause) { setError(message(cause)); } finally { setBusy(""); } }
  async function download(id: number, name: string) { setBusy(`download-${id}`); setError(""); try { await downloadDocument(`/student/internship-onboarding/documents/${id}/download`, name); } catch (cause) { setError(message(cause)); } finally { setBusy(""); } }
  async function confirmDiary() { setBusy("diary"); setError(""); try { setOnboarding((await api.post<InternshipOnboarding>("/student/internship-onboarding/diary/confirm")).data); } catch (cause) { setError(message(cause)); } finally { setBusy(""); } }
  return <ProtectedRoute role="STUDENT"><AppFrame><main className="mx-auto max-w-5xl px-5 py-10 sm:px-8"><Link href="/student/dashboard" className="text-sm font-semibold text-blue-700">← Back to dashboard</Link><div className="mt-5"><p className="text-sm font-semibold text-blue-700">Internship registration</p><h1 className="mt-2 text-3xl font-bold tracking-tight">Internship Onboarding</h1><p className="mt-2 text-slate-600">Complete the preparation steps before entering internship details.</p></div>
    {error && <p className="mt-6 rounded-xl bg-red-50 p-4 text-sm text-red-700">{error}</p>}
    {loading || !onboarding ? <p className="py-20 text-center text-sm text-slate-500">Loading internship status…</p> : <div className="mt-8 space-y-5">
      <section className="rounded-2xl border border-slate-200 bg-white p-6 sm:p-8"><div className="flex items-start justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[0.18em] text-slate-500">Current Status</p><h2 className="mt-2 text-xl font-bold">Internship preparation</h2></div><WorkflowBadge status={onboarding.workflowStatus}/></div>{onboarding.workflowStatus === "NOT_SECURED" && <div className="mt-6"><p className="text-sm text-slate-600">Once you have secured an internship, begin the registration workflow here.</p><button disabled={!!busy} onClick={secure} className="mt-4 rounded-xl bg-blue-700 px-5 py-3 text-sm font-semibold text-white disabled:opacity-50">{busy === "secure" ? "Starting…" : "Internship Secured"}</button></div>}</section>
      {onboarding.id && <section className="rounded-2xl border border-slate-200 bg-white p-6 sm:p-8"><h2 className="text-lg font-bold">1. Internship Source</h2><p className="mt-2 text-sm text-slate-600">Select how this internship was secured.</p><div className="mt-4 grid gap-3 sm:grid-cols-3">{sourceOptions.map(option => <button key={option.value} disabled={!!busy} onClick={() => selectSource(option.value)} className={`rounded-xl border px-4 py-4 text-left text-sm font-semibold disabled:opacity-50 ${onboarding.source === option.value ? "border-blue-700 bg-blue-50 text-blue-800" : "border-slate-300 hover:border-blue-400"}`}><span className="mr-2">{onboarding.source === option.value ? "●" : "○"}</span>{option.label}</button>)}</div></section>}
      {onboarding.source && <section className="rounded-2xl border border-slate-200 bg-white p-6 sm:p-8"><div className="flex flex-wrap items-end justify-between gap-2"><div><h2 className="text-lg font-bold">2. Required Documents</h2><p className="mt-2 text-sm text-slate-600">PDF, JPEG, or PNG · maximum 10 MB each</p></div><p className="text-sm font-bold text-blue-700">{onboarding.documentsCompleted} of {onboarding.documentsRequired} completed</p></div><div className="mt-5 divide-y divide-slate-100 rounded-xl border border-slate-200">{onboarding.documents.map(document => <div key={document.documentType} className="flex flex-wrap items-center justify-between gap-3 px-4 py-4"><div><p className="text-sm font-semibold"><span className={document.uploaded ? "text-emerald-600" : "text-slate-400"}>{document.uploaded ? "✓" : "○"}</span> {document.documentTypeLabel}</p><p className="mt-1 text-xs text-slate-500">{document.uploaded ? `${document.originalFileName} · ${fileSize(document.fileSize)}` : "Required"}</p></div><div className="flex gap-2">{document.uploaded && document.id && <button disabled={!!busy} onClick={() => download(document.id!, document.originalFileName!)} className="rounded-lg border border-slate-300 px-3 py-2 text-xs font-semibold disabled:opacity-50">View</button>}<label className={`cursor-pointer rounded-lg px-3 py-2 text-xs font-semibold ${busy ? "pointer-events-none opacity-50" : ""} ${document.uploaded ? "border border-slate-300" : "bg-blue-700 text-white"}`}>{busy === document.documentType ? "Uploading…" : document.uploaded ? "Replace" : "Upload"}<input type="file" accept=".pdf,.jpg,.jpeg,.png,application/pdf,image/jpeg,image/png" onChange={event => upload(document.documentType, event)} className="sr-only"/></label></div></div>)}</div></section>}
      {onboarding.source && <section className="rounded-2xl border border-slate-200 bg-white p-6 sm:p-8"><h2 className="text-lg font-bold">3. Internship Diary</h2>{onboarding.diaryIssued ? <div className="mt-4 rounded-xl bg-emerald-50 p-4"><p className="font-semibold text-emerald-800">✓ Internship Diary received</p><p className="mt-1 text-sm text-emerald-700">Confirmed {onboarding.diaryIssuedAt && new Date(onboarding.diaryIssuedAt).toLocaleString()}</p><Link href="/student/internship/details" className="mt-5 inline-block rounded-xl bg-blue-700 px-5 py-3 text-sm font-semibold text-white">{onboarding.workflowStatus === "INTERNSHIP_DETAILS_COMPLETE" ? "View Internship Details" : "Continue to Internship Details"}</Link></div> : onboarding.workflowStatus !== "DOCUMENTS_COMPLETE" ? <p className="mt-3 text-sm text-slate-600">Available after required documents are completed.</p> : <div className="mt-4"><label className="flex items-start gap-3 text-sm font-medium"><input type="checkbox" checked={diaryConfirmed} onChange={event => setDiaryConfirmed(event.target.checked)} className="mt-0.5 h-4 w-4"/>I confirm that I have received my Internship Diary.</label><button disabled={!diaryConfirmed || !!busy} onClick={confirmDiary} className="mt-4 rounded-xl bg-blue-700 px-5 py-3 text-sm font-semibold text-white disabled:opacity-40">{busy === "diary" ? "Confirming…" : "Confirm Diary Received"}</button></div>}</section>}
    </div>}
  </main></AppFrame></ProtectedRoute>;
}
