package edu.institution.ims.attendance;

public enum VerificationReason {
    VERIFIED_GEOFENCE,
    EXPECTED_LOCATION_NOT_CONFIRMED,
    LIVE_LOCATION_UNAVAILABLE,
    GPS_ACCURACY_TOO_LOW,
    OUTSIDE_GEOFENCE,
    METADATA_CONTRADICTION,
    PHYSICAL_VERIFICATION_NOT_APPLICABLE,
    REMOTE_EVIDENCE_COMPLETE,
    HYBRID_SCHEDULE_NOT_CONFIGURED
}
