"use client";

import { FormEvent, useState } from "react";
import { InternshipDetailsFormData } from "@/lib/internship-details";

export function InternshipDetailsForm({ initial, saving, fieldErrors, onCancel, onSubmit }: { initial: InternshipDetailsFormData; saving: boolean; fieldErrors: Record<string,string>; onCancel?: () => void; onSubmit: (data: InternshipDetailsFormData) => void }) {
  const [data, setData] = useState(initial); const set = (field: keyof InternshipDetailsFormData, value: string) => setData(current => ({...current, [field]: value}));
  function submit(event: FormEvent) { event.preventDefault(); onSubmit(data); }
  return <form onSubmit={submit} className="space-y-5"><FormSection title="1. Company Information"><Field label="Company Name" error={fieldErrors.companyName}><input required maxLength={200} value={data.companyName} onChange={event => set("companyName", event.target.value)} className="input"/></Field><Field label="Type of Company" error={fieldErrors.companyType}><select required value={data.companyType} onChange={event => set("companyType", event.target.value)} className="input"><option value="">Select company type</option><option value="IT">IT</option><option value="MANUFACTURING">Manufacturing</option><option value="CORE">Core</option><option value="OTHER">Other</option></select></Field>{data.companyType === "OTHER" && <Field label="Other Company Type" error={fieldErrors.otherCompanyType}><input required maxLength={100} value={data.otherCompanyType} onChange={event => set("otherCompanyType", event.target.value)} className="input"/></Field>}<Field wide label="Address of Company" error={fieldErrors.companyAddress}><textarea required maxLength={1000} rows={3} value={data.companyAddress} onChange={event => set("companyAddress", event.target.value)} className="input resize-y"/></Field><Field label="Company Phone Number" error={fieldErrors.companyPhone}><input required type="tel" value={data.companyPhone} onChange={event => set("companyPhone", event.target.value)} className="input"/></Field></FormSection>
    <FormSection title="2. Industry Supervisor"><Field label="Supervisor Name" error={fieldErrors.industrySupervisorName}><input required maxLength={150} value={data.industrySupervisorName} onChange={event => set("industrySupervisorName", event.target.value)} className="input"/></Field><Field label="Designation" error={fieldErrors.industrySupervisorDesignation}><input required maxLength={150} value={data.industrySupervisorDesignation} onChange={event => set("industrySupervisorDesignation", event.target.value)} className="input"/></Field><Field label="Contact Number" error={fieldErrors.industrySupervisorContact}><input required type="tel" value={data.industrySupervisorContact} onChange={event => set("industrySupervisorContact", event.target.value)} className="input"/></Field></FormSection>
    <FormSection title="3. Internship Duration"><Field label="Duration in Months" error={fieldErrors.durationMonths}><input required type="number" min="1" step="1" value={data.durationMonths} onChange={event => set("durationMonths", event.target.value)} className="input"/></Field><Field label="Start Date" error={fieldErrors.startDate}><input required type="date" value={data.startDate} onChange={event => set("startDate", event.target.value)} className="input"/></Field><Field label="End Date" error={fieldErrors.endDate}><input required type="date" min={data.startDate || undefined} value={data.endDate} onChange={event => set("endDate", event.target.value)} className="input"/></Field><Field label="Total Number of Weeks" error={fieldErrors.totalWeeks}><input required type="number" min="1" step="1" value={data.totalWeeks} onChange={event => set("totalWeeks", event.target.value)} className="input"/></Field></FormSection>
    <FormSection title="4. Internship Arrangement"><Field label="Internship Mode" error={fieldErrors.internshipMode}><select required value={data.internshipMode} onChange={event => set("internshipMode", event.target.value)} className="input"><option value="">Select internship mode</option><option value="OFFICE_REPORTING">Office Reporting</option><option value="HYBRID">Hybrid</option><option value="ONLINE">Online</option><option value="COLLEGE_REPORTING">College Reporting</option></select></Field><Field label="Stipend Per Month (₹)" error={fieldErrors.stipendPerMonth}><input required type="number" min="0" step="0.01" value={data.stipendPerMonth} onChange={event => set("stipendPerMonth", event.target.value)} className="input"/></Field><Field wide label="Full-Time Employment Opportunity after Internship" error={fieldErrors.fullTimeEmploymentOffered}><div className="flex gap-3">{[["true","Yes"],["false","No"]].map(([value,label]) => <label key={value} className={`cursor-pointer rounded-xl border px-5 py-3 text-sm font-semibold ${data.fullTimeEmploymentOffered === value ? "border-blue-700 bg-blue-50 text-blue-800" : "border-slate-300"}`}><input required type="radio" name="employment" value={value} checked={data.fullTimeEmploymentOffered === value} onChange={event => set("fullTimeEmploymentOffered", event.target.value)} className="mr-2"/>{label}</label>)}</div></Field></FormSection>
    <div className="flex gap-3"><button disabled={saving} className="rounded-xl bg-blue-700 px-6 py-3 text-sm font-semibold text-white disabled:opacity-50">{saving ? "Saving…" : "Save Internship Details"}</button>{onCancel && <button type="button" onClick={onCancel} className="rounded-xl border border-slate-300 px-6 py-3 text-sm font-semibold">Cancel</button>}</div>
  </form>;
}

function FormSection({ title, children }: { title: string; children: React.ReactNode }) { return <section className="rounded-2xl border border-slate-200 bg-white p-6 sm:p-8"><h2 className="text-lg font-bold">{title}</h2><div className="mt-5 grid gap-5 sm:grid-cols-2">{children}</div></section>; }
function Field({ label, error, wide, children }: { label: string; error?: string; wide?: boolean; children: React.ReactNode }) { return <label className={wide ? "sm:col-span-2" : ""}><span className="mb-2 block text-sm font-semibold">{label}</span>{children}{error && <span className="mt-1 block text-xs text-red-700">{error}</span>}</label>; }
