"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { AppFrame } from "@/components/AppFrame";
import { ProtectedRoute } from "@/components/ProtectedRoute";
import { StatusBadge } from "@/components/StatusBadge";
import { WorkflowBadge } from "@/components/WorkflowBadge";
import { api } from "@/lib/api";
import { InternshipDetails } from "@/lib/internship-details";
import { InternshipOnboarding } from "@/lib/internship-onboarding";
import { StudentProfile } from "@/lib/student-profile";

export default function StudentDashboard() {
  const [profile, setProfile] = useState<StudentProfile | null>(null); const [onboarding, setOnboarding] = useState<InternshipOnboarding | null>(null); const [details, setDetails] = useState<InternshipDetails | null>(null); const [loading, setLoading] = useState(true); const [starting, setStarting] = useState(false); const [error, setError] = useState("");
  useEffect(() => { Promise.all([api.get<StudentProfile>("/student/profile").then(r => r.data).catch(() => null), api.get<InternshipOnboarding>("/student/internship-onboarding").then(r => r.data), api.get<InternshipDetails>("/student/internship").then(r => r.data).catch(() => null)]).then(([studentProfile, internship, internshipDetails]) => { setProfile(studentProfile); setOnboarding(internship); setDetails(internshipDetails); }).catch(() => setError("Dashboard status could not be loaded.")).finally(() => setLoading(false)); }, []);
  async function secureInternship() { setStarting(true); setError(""); try { const { data } = await api.post<InternshipOnboarding>("/student/internship-onboarding/secure"); setOnboarding(data); window.location.assign("/student/internship"); } catch { setError("Complete your student profile before registering an internship."); } finally { setStarting(false); } }
  return <ProtectedRoute role="STUDENT"><AppFrame><main className="mx-auto max-w-7xl px-5 py-10 sm:px-8">
    <p className="text-sm font-semibold text-blue-700">Student workspace</p><h1 className="mt-2 text-3xl font-bold tracking-tight text-slate-950">Student Dashboard</h1><p className="mt-2 text-slate-600">Keep your institutional information current before beginning internship workflows.</p>
    <div className="mt-9 grid gap-5 lg:grid-cols-2">
      <section className="rounded-2xl border border-slate-200 bg-white p-7"><div className="flex items-start justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[0.18em] text-blue-700">Student Profile</p><h2 className="mt-3 text-xl font-bold">{loading ? "Checking profile…" : profile ? "Profile Completed" : "Complete Your Student Profile"}</h2></div>{!loading && <StatusBadge status={profile ? "COMPLETE" : "INCOMPLETE"}/>}</div>
        <p className="mt-3 text-sm leading-6 text-slate-600">{profile ? "Your institutional profile is available to you and the III Cell." : "Provide the institutional information required to continue your internship journey."}</p>
        {!loading && <div className="mt-6 flex gap-3">{profile ? <><Link href="/student/profile" className="rounded-xl bg-blue-700 px-5 py-3 text-sm font-semibold text-white">View Profile</Link><Link href="/student/profile?edit=true" className="rounded-xl border border-slate-300 px-5 py-3 text-sm font-semibold">Edit Profile</Link></> : <Link href="/student/profile" className="rounded-xl bg-blue-700 px-5 py-3 text-sm font-semibold text-white">Complete Profile</Link>}</div>}
      </section>
      <section className="rounded-2xl border border-slate-200 bg-white p-7"><div className="flex items-start justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[0.18em] text-slate-500">Internship</p><h2 className="mt-3 text-xl font-bold">{loading ? "Checking status…" : details ? "Internship Details Completed" : onboarding?.workflowStatus === "DIARY_ISSUED" ? "Internship Details Pending" : onboarding?.workflowStatus === "NOT_SECURED" ? "Internship Status" : "Internship Onboarding"}</h2></div>{!loading && onboarding && <WorkflowBadge status={onboarding.workflowStatus}/>}</div>
        {!loading && !profile ? <p className="mt-4 text-sm leading-6 text-slate-600">Complete your student profile before registering an internship.</p> : !loading && onboarding ? <>{details ? <div className="mt-5 grid grid-cols-2 gap-3 rounded-xl bg-slate-50 p-4 text-sm"><div><p className="text-xs text-slate-500">Company</p><p className="mt-1 font-semibold">{details.companyName}</p></div><div><p className="text-xs text-slate-500">Mode</p><p className="mt-1 font-semibold">{details.internshipModeLabel}</p></div><div><p className="text-xs text-slate-500">Start Date</p><p className="mt-1 font-semibold">{details.startDate}</p></div><div><p className="text-xs text-slate-500">End Date</p><p className="mt-1 font-semibold">{details.endDate}</p></div></div> : <div className="mt-5 grid grid-cols-3 gap-3 rounded-xl bg-slate-50 p-4 text-sm"><div><p className="text-xs text-slate-500">Source</p><p className="mt-1 font-semibold">{onboarding.sourceLabel ?? "—"}</p></div><div><p className="text-xs text-slate-500">Documents</p><p className="mt-1 font-semibold">{onboarding.documentsCompleted} / {onboarding.documentsRequired}</p></div><div><p className="text-xs text-slate-500">Diary</p><p className="mt-1 font-semibold">{onboarding.diaryIssued ? "Received" : "Not issued"}</p></div></div>}<div className="mt-5 flex flex-wrap gap-3">{details ? <><Link href="/student/internship/details" className="rounded-xl bg-blue-700 px-5 py-3 text-sm font-semibold text-white">View Details</Link><Link href="/student/internship/details#edit" className="rounded-xl border border-slate-300 px-5 py-3 text-sm font-semibold">Edit Details</Link></> : onboarding.workflowStatus === "NOT_SECURED" ? <button disabled={starting} onClick={secureInternship} className="rounded-xl bg-blue-700 px-5 py-3 text-sm font-semibold text-white disabled:opacity-50">{starting ? "Starting…" : "Internship Secured"}</button> : onboarding.workflowStatus === "DIARY_ISSUED" ? <Link href="/student/internship/details" className="rounded-xl bg-blue-700 px-5 py-3 text-sm font-semibold text-white">Complete Internship Details</Link> : <Link href="/student/internship" className="inline-block rounded-xl bg-blue-700 px-5 py-3 text-sm font-semibold text-white">Continue Internship Registration</Link>}</div></> : null}
        {error && <p className="mt-4 text-sm text-red-700">{error}</p>}
      </section>
    </div>
  </main></AppFrame></ProtectedRoute>;
}
