ALTER TABLE attendance_records DROP CONSTRAINT ck_attendance_records_submission_type;
ALTER TABLE attendance_records ADD CONSTRAINT ck_attendance_records_submission_type
    CHECK (submission_type IN ('BASIC', 'PHYSICAL_CAPTURE'));

CREATE TABLE internship_locations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    internship_id BIGINT NOT NULL,
    latitude NUMERIC(9, 6) NOT NULL,
    longitude NUMERIC(10, 6) NOT NULL,
    geofence_radius_meters NUMERIC(8, 2) NOT NULL,
    status VARCHAR(20) NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    confirmed_at TIMESTAMP(6) WITH TIME ZONE,
    confirmed_by BIGINT,
    CONSTRAINT pk_internship_locations PRIMARY KEY (id),
    CONSTRAINT uk_internship_locations_internship UNIQUE (internship_id),
    CONSTRAINT fk_internship_locations_internship FOREIGN KEY (internship_id) REFERENCES internship_details (id),
    CONSTRAINT fk_internship_locations_confirmer FOREIGN KEY (confirmed_by) REFERENCES users (id),
    CONSTRAINT ck_internship_locations_latitude CHECK (latitude BETWEEN -90 AND 90),
    CONSTRAINT ck_internship_locations_longitude CHECK (longitude BETWEEN -180 AND 180),
    CONSTRAINT ck_internship_locations_radius CHECK (geofence_radius_meters BETWEEN 10 AND 5000),
    CONSTRAINT ck_internship_locations_status CHECK (status IN ('PENDING', 'CONFIRMED')),
    CONSTRAINT ck_internship_locations_confirmation CHECK (
        (status = 'PENDING' AND confirmed_at IS NULL AND confirmed_by IS NULL)
        OR (status = 'CONFIRMED' AND confirmed_at IS NOT NULL AND confirmed_by IS NOT NULL)
    )
);

CREATE INDEX idx_internship_locations_status ON internship_locations (status);

CREATE TABLE attendance_evidence (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    attendance_id BIGINT NOT NULL,
    latitude NUMERIC(9, 6),
    longitude NUMERIC(10, 6),
    gps_accuracy_meters NUMERIC(8, 2),
    expected_latitude NUMERIC(9, 6),
    expected_longitude NUMERIC(10, 6),
    geofence_radius_meters NUMERIC(8, 2),
    distance_meters NUMERIC(10, 2),
    location_check_passed BOOLEAN,
    exif_timestamp TIMESTAMP(6) WITH TIME ZONE,
    exif_latitude NUMERIC(9, 6),
    exif_longitude NUMERIC(10, 6),
    metadata_consistent BOOLEAN,
    camera_capture_used BOOLEAN NOT NULL,
    verification_reason VARCHAR(80) NOT NULL,
    image_media_type VARCHAR(50) NOT NULL,
    image_size_bytes BIGINT NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT pk_attendance_evidence PRIMARY KEY (id),
    CONSTRAINT uk_attendance_evidence_attendance UNIQUE (attendance_id),
    CONSTRAINT fk_attendance_evidence_attendance FOREIGN KEY (attendance_id) REFERENCES attendance_records (id),
    CONSTRAINT ck_attendance_evidence_latitude CHECK (latitude IS NULL OR latitude BETWEEN -90 AND 90),
    CONSTRAINT ck_attendance_evidence_longitude CHECK (longitude IS NULL OR longitude BETWEEN -180 AND 180),
    CONSTRAINT ck_attendance_evidence_accuracy CHECK (gps_accuracy_meters IS NULL OR gps_accuracy_meters > 0),
    CONSTRAINT ck_attendance_evidence_expected_latitude CHECK (expected_latitude IS NULL OR expected_latitude BETWEEN -90 AND 90),
    CONSTRAINT ck_attendance_evidence_expected_longitude CHECK (expected_longitude IS NULL OR expected_longitude BETWEEN -180 AND 180),
    CONSTRAINT ck_attendance_evidence_radius CHECK (geofence_radius_meters IS NULL OR geofence_radius_meters BETWEEN 10 AND 5000),
    CONSTRAINT ck_attendance_evidence_distance CHECK (distance_meters IS NULL OR distance_meters >= 0),
    CONSTRAINT ck_attendance_evidence_exif_latitude CHECK (exif_latitude IS NULL OR exif_latitude BETWEEN -90 AND 90),
    CONSTRAINT ck_attendance_evidence_exif_longitude CHECK (exif_longitude IS NULL OR exif_longitude BETWEEN -180 AND 180),
    CONSTRAINT ck_attendance_evidence_image_size CHECK (image_size_bytes > 0)
);

CREATE INDEX idx_attendance_evidence_reason ON attendance_evidence (verification_reason);
