ALTER TABLE attendance_records DROP CONSTRAINT ck_attendance_records_submission_type;
ALTER TABLE attendance_records ADD CONSTRAINT ck_attendance_records_submission_type
    CHECK (submission_type IN ('BASIC', 'PHYSICAL_CAPTURE', 'REMOTE_CAPTURE'));

ALTER TABLE attendance_evidence ADD COLUMN daily_work_summary VARCHAR(1000);
ALTER TABLE attendance_evidence ADD COLUMN expected_work_mode VARCHAR(20);
ALTER TABLE attendance_evidence ADD CONSTRAINT ck_attendance_evidence_work_summary
    CHECK (daily_work_summary IS NULL OR CHAR_LENGTH(daily_work_summary) BETWEEN 20 AND 1000);
ALTER TABLE attendance_evidence ADD CONSTRAINT ck_attendance_evidence_work_mode
    CHECK (expected_work_mode IS NULL OR expected_work_mode IN ('OFFICE', 'REMOTE'));

CREATE TABLE hybrid_work_schedule (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    internship_id BIGINT NOT NULL,
    day_of_week VARCHAR(12) NOT NULL,
    work_mode VARCHAR(20) NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT pk_hybrid_work_schedule PRIMARY KEY (id),
    CONSTRAINT fk_hybrid_work_schedule_internship FOREIGN KEY (internship_id) REFERENCES internship_details (id),
    CONSTRAINT uk_hybrid_work_schedule_day UNIQUE (internship_id, day_of_week),
    CONSTRAINT ck_hybrid_work_schedule_day CHECK (day_of_week IN (
        'MONDAY', 'TUESDAY', 'WEDNESDAY', 'THURSDAY', 'FRIDAY', 'SATURDAY', 'SUNDAY'
    )),
    CONSTRAINT ck_hybrid_work_schedule_mode CHECK (work_mode IN ('OFFICE', 'REMOTE'))
);

CREATE INDEX idx_hybrid_work_schedule_internship ON hybrid_work_schedule (internship_id);
