CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    email VARCHAR(254) NOT NULL,
    password_hash VARCHAR(60) NOT NULL,
    role VARCHAR(20) NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (id),
    CONSTRAINT uk_users_email UNIQUE (email),
    CONSTRAINT chk_users_role CHECK (role IN ('ADMIN', 'STUDENT', 'HOD', 'MENTOR'))
);
CREATE INDEX idx_users_role ON users (role);
CREATE INDEX idx_users_active ON users (active);

CREATE TABLE student_accounts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    user_id BIGINT NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT pk_student_accounts PRIMARY KEY (id),
    CONSTRAINT uk_student_accounts_user UNIQUE (user_id),
    CONSTRAINT fk_student_accounts_user FOREIGN KEY (user_id) REFERENCES users (id)
);
