CREATE TABLE internship_onboarding (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    student_user_id BIGINT NOT NULL,
    source VARCHAR(20) NULL,
    workflow_status VARCHAR(30) NOT NULL,
    secured_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    documents_completed_at TIMESTAMP(6) WITH TIME ZONE NULL,
    diary_issued BOOLEAN NOT NULL DEFAULT FALSE,
    diary_issued_at TIMESTAMP(6) WITH TIME ZONE NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT pk_internship_onboarding PRIMARY KEY (id),
    CONSTRAINT uk_internship_onboarding_student UNIQUE (student_user_id),
    CONSTRAINT fk_internship_onboarding_student FOREIGN KEY (student_user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT chk_internship_onboarding_source CHECK (source IS NULL OR source IN ('DEPARTMENT','CDC','SELF')),
    CONSTRAINT chk_internship_onboarding_status CHECK (workflow_status IN ('NOT_SECURED','INTERNSHIP_SECURED','DOCUMENTS_PENDING','DOCUMENTS_COMPLETE','DIARY_ISSUED')),
    CONSTRAINT chk_internship_onboarding_diary CHECK (
        (diary_issued = TRUE AND workflow_status = 'DIARY_ISSUED' AND diary_issued_at IS NOT NULL)
        OR (diary_issued = FALSE AND workflow_status <> 'DIARY_ISSUED' AND diary_issued_at IS NULL)
    )
);

CREATE INDEX idx_internship_onboarding_status ON internship_onboarding (workflow_status);
CREATE INDEX idx_internship_onboarding_source ON internship_onboarding (source);

CREATE TABLE internship_documents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    onboarding_id BIGINT NOT NULL,
    document_type VARCHAR(30) NOT NULL,
    original_file_name VARCHAR(255) NOT NULL,
    storage_key VARCHAR(255) NOT NULL,
    content_type VARCHAR(100) NOT NULL,
    file_size BIGINT NOT NULL,
    uploaded_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT pk_internship_documents PRIMARY KEY (id),
    CONSTRAINT uk_internship_documents_type UNIQUE (onboarding_id, document_type),
    CONSTRAINT uk_internship_documents_storage_key UNIQUE (storage_key),
    CONSTRAINT fk_internship_documents_onboarding FOREIGN KEY (onboarding_id) REFERENCES internship_onboarding (id) ON DELETE CASCADE,
    CONSTRAINT chk_internship_documents_type CHECK (document_type IN ('OFFER_LETTER','UNDERTAKING','DEPARTMENT_NOC','STUDENT_NOC')),
    CONSTRAINT chk_internship_documents_file_size CHECK (file_size > 0)
);

CREATE INDEX idx_internship_documents_onboarding ON internship_documents (onboarding_id);
