ALTER TABLE internship_onboarding DROP CONSTRAINT chk_internship_onboarding_status;
ALTER TABLE internship_onboarding DROP CONSTRAINT chk_internship_onboarding_diary;

ALTER TABLE internship_onboarding ADD CONSTRAINT chk_internship_onboarding_status CHECK (
    workflow_status IN ('NOT_SECURED','INTERNSHIP_SECURED','DOCUMENTS_PENDING','DOCUMENTS_COMPLETE','DIARY_ISSUED','INTERNSHIP_DETAILS_COMPLETE')
);
ALTER TABLE internship_onboarding ADD CONSTRAINT chk_internship_onboarding_diary CHECK (
    (diary_issued = TRUE AND workflow_status IN ('DIARY_ISSUED','INTERNSHIP_DETAILS_COMPLETE') AND diary_issued_at IS NOT NULL)
    OR (diary_issued = FALSE AND workflow_status NOT IN ('DIARY_ISSUED','INTERNSHIP_DETAILS_COMPLETE') AND diary_issued_at IS NULL)
);

CREATE TABLE internship_details (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    onboarding_id BIGINT NOT NULL,
    company_name VARCHAR(200) NOT NULL,
    company_type VARCHAR(30) NOT NULL,
    other_company_type VARCHAR(100) NULL,
    company_address VARCHAR(1000) NOT NULL,
    company_phone VARCHAR(25) NOT NULL,
    industry_supervisor_name VARCHAR(150) NOT NULL,
    industry_supervisor_designation VARCHAR(150) NOT NULL,
    industry_supervisor_contact VARCHAR(25) NOT NULL,
    duration_months INT NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    total_weeks INT NOT NULL,
    internship_mode VARCHAR(30) NOT NULL,
    stipend_per_month DECIMAL(12,2) NOT NULL,
    full_time_employment_offered BOOLEAN NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT pk_internship_details PRIMARY KEY (id),
    CONSTRAINT uk_internship_details_onboarding UNIQUE (onboarding_id),
    CONSTRAINT fk_internship_details_onboarding FOREIGN KEY (onboarding_id) REFERENCES internship_onboarding (id) ON DELETE CASCADE,
    CONSTRAINT chk_internship_details_company_type CHECK (company_type IN ('IT','MANUFACTURING','CORE','OTHER')),
    CONSTRAINT chk_internship_details_other_type CHECK (
        (company_type = 'OTHER' AND other_company_type IS NOT NULL AND CHAR_LENGTH(TRIM(other_company_type)) > 0)
        OR (company_type <> 'OTHER' AND other_company_type IS NULL)
    ),
    CONSTRAINT chk_internship_details_dates CHECK (end_date > start_date),
    CONSTRAINT chk_internship_details_duration CHECK (duration_months > 0 AND total_weeks > 0),
    CONSTRAINT chk_internship_details_stipend CHECK (stipend_per_month >= 0),
    CONSTRAINT chk_internship_details_mode CHECK (internship_mode IN ('OFFICE_REPORTING','HYBRID','ONLINE','COLLEGE_REPORTING'))
);

CREATE INDEX idx_internship_details_company_name ON internship_details (company_name);
CREATE INDEX idx_internship_details_company_type ON internship_details (company_type);
CREATE INDEX idx_internship_details_mode ON internship_details (internship_mode);
CREATE INDEX idx_internship_details_dates ON internship_details (start_date, end_date);
