CREATE TABLE mentor_profiles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    user_id BIGINT NOT NULL,
    name VARCHAR(150) NOT NULL,
    employee_id VARCHAR(50) NOT NULL,
    department VARCHAR(150) NOT NULL,
    designation VARCHAR(150) NOT NULL,
    phone VARCHAR(25) NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT pk_mentor_profiles PRIMARY KEY (id),
    CONSTRAINT uk_mentor_profiles_user UNIQUE (user_id),
    CONSTRAINT uk_mentor_profiles_employee_id UNIQUE (employee_id),
    CONSTRAINT fk_mentor_profiles_user FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE INDEX idx_mentor_profiles_name ON mentor_profiles (name);
CREATE INDEX idx_mentor_profiles_department ON mentor_profiles (department);
