CREATE TABLE mentor_student_assignments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    mentor_user_id BIGINT NOT NULL,
    student_user_id BIGINT NOT NULL,
    assigned_by BIGINT NOT NULL,
    assigned_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    active BOOLEAN NOT NULL,
    ended_at TIMESTAMP(6) WITH TIME ZONE,
    active_student_user_id BIGINT,
    CONSTRAINT pk_mentor_student_assignments PRIMARY KEY (id),
    CONSTRAINT fk_mentor_student_assignments_mentor FOREIGN KEY (mentor_user_id) REFERENCES users (id),
    CONSTRAINT fk_mentor_student_assignments_student FOREIGN KEY (student_user_id) REFERENCES users (id),
    CONSTRAINT fk_mentor_student_assignments_admin FOREIGN KEY (assigned_by) REFERENCES users (id),
    CONSTRAINT uk_mentor_student_assignments_active_student UNIQUE (active_student_user_id),
    CONSTRAINT ck_mentor_student_assignments_distinct_users CHECK (mentor_user_id <> student_user_id),
    CONSTRAINT ck_mentor_student_assignments_active_state CHECK (
        (active = TRUE AND ended_at IS NULL AND active_student_user_id = student_user_id)
        OR
        (active = FALSE AND ended_at IS NOT NULL AND active_student_user_id IS NULL)
    )
);

CREATE INDEX idx_mentor_student_assignments_mentor_active
    ON mentor_student_assignments (mentor_user_id, active);
CREATE INDEX idx_mentor_student_assignments_student_history
    ON mentor_student_assignments (student_user_id, assigned_at);
CREATE INDEX idx_mentor_student_assignments_assigned_by
    ON mentor_student_assignments (assigned_by);
