CREATE TABLE attendance_records (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    student_user_id BIGINT NOT NULL,
    internship_id BIGINT NOT NULL,
    attendance_date DATE NOT NULL,
    attendance_result VARCHAR(20) NOT NULL,
    verification_status VARCHAR(20) NOT NULL,
    submission_type VARCHAR(30) NOT NULL,
    server_submitted_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT pk_attendance_records PRIMARY KEY (id),
    CONSTRAINT fk_attendance_records_student FOREIGN KEY (student_user_id) REFERENCES users (id),
    CONSTRAINT fk_attendance_records_internship FOREIGN KEY (internship_id) REFERENCES internship_details (id),
    CONSTRAINT uk_attendance_records_student_internship_date UNIQUE (student_user_id, internship_id, attendance_date),
    CONSTRAINT ck_attendance_records_result CHECK (attendance_result IN ('PRESENT', 'ABSENT')),
    CONSTRAINT ck_attendance_records_verification CHECK (verification_status IN ('UNVERIFIED', 'VERIFIED')),
    CONSTRAINT ck_attendance_records_submission_type CHECK (submission_type IN ('BASIC'))
);

CREATE INDEX idx_attendance_records_student_date
    ON attendance_records (student_user_id, attendance_date);
CREATE INDEX idx_attendance_records_internship_date
    ON attendance_records (internship_id, attendance_date);
CREATE INDEX idx_attendance_records_date_verification
    ON attendance_records (attendance_date, verification_status);
